### ISSUE TITLE
Java memory requirements with bioformats command line tools

### ISSUE THREAD

**Issue by hackermd** [TissueMAPS/TmLibrary#34]
The [showinf](https://www.openmicroscopy.org/site/support/bio-formats5.3/users/comlinetools/display.html) cli tool takes a lot of memory. Upon migration from Ubuntu 14.04 with JDK 7 to CentOS 7 or Ubuntu 16.04 with JDK 8, a single job requires more than 4GB of memory.

We need to find a way to restrict the JVM memory usage.

**Comment by HackerMD** [comment]
[BF_PROFILE](https://www.openmicroscopy.org/site/support/bio-formats5.3/users/comlinetools/#profiling) might be helpful.

**Comment by riccardomurri** [comment]
In short, the new java needs the following options:

```
java -XX:+UseSerialGC -XX:+PrintGC -XX:-UseCompressedOops -XX:-UseCompressedClassPointers -Xmx$(( $MAX_MEMORY_MB - 512))m
```

(I'll post a detailed explanation later on -- but now I just need to save this info after a hard 2 days digging...)

**Comment by riccardomurri** [comment]
Apparently, a major change from JDK 7 to JDK 8 was the [introduction of a new "Metaspace" memory sector for keeping class code and other metadata][1]. As described by [Oracle's official docs][0] (see section "Class Metadata"):

> Java classes have an internal representation within Java Hotspot VM and are referred to as class metadata. [...] The amount of native memory that can be used for class metadata is by default unlimited. Use the option `MaxMetaspaceSize` to put an upper limit on the amount of native memory used for class metadata.

There are corresponding flags for setting the minimum, initial Metaspace size, and the size of chunks used when resizing. All of these apparently have sensible defaults (use [`java -XX:+UnlockDiagnosticVMOptions -XX:+PrintFlagsFinal -version`][2]) to print (all sizes are in *bytes*)::

```
uintx InitialBootClassLoaderMetaspaceSize       = 4194304                             {product}
uintx MaxMetaspaceExpansion                     = 5451776                             {product}
uintx MaxMetaspaceFreeRatio                     = 70                                  {product}
uintx MaxMetaspaceSize                          = 18446744073709547520                    {product}
uintx MetaspaceSize                             = 21807104                            {pd product}
uintx MinMetaspaceExpansion                     = 339968                              {product}
uintx MinMetaspaceFreeRatio                     = 40                                  {product}
 bool UseLargePagesInMetaspace                  = false                               {product}
```

However, the [JDK8 docs][0] continue (emphasis added):

> If `UseCompressedOops` is turned on and `UseCompressedClassesPointers` is used, then two logically different areas of native memory are used for class metadata. [...] The size of the region can be set with `CompressedClassSpaceSize` and **is 1 gigabyte (GB) by default. The space for the compressed class pointers is reserved as space allocated by mmap at initialization** [...]

What is probably not emphasized enough by the documentation is that *these three options are "on" by default*:

```
uintx CompressedClassSpaceSize                  = 1073741824                          {product}
 ...
 bool UseCompressedClassPointers               := true                                {lp64_product}
 bool UseCompressedOops                        := true                                {lp64_product}
```

Therefore, a JVM with the default settings needs *at least* 1GB of memory to run, to which the size of the Java heap and JVM process overhead should be added.  Indeed, you cannot even run `java -version` with less than 1.5GB of memory!

[0]: https://docs.oracle.com/javase/8/docs/technotes/guides/vm/gctuning/considerations.html
[1]: https://dzone.com/articles/java-8-permgen-metaspace
[2]: https://stackoverflow.com/questions/10486375/print-all-jvm-flags
[3]: http://mail.openjdk.java.net/pipermail/hotspot-runtime-dev/2015-April/014425.html

So, one easy escape route would be to ensure that all jobs involving the JVM are allocated at least 1.5GB.

However, although not completely clear from the documentation, turning off the "compressed class" feature (which can be done with command-line options) removes the entire "compressed class space" from the Metaspace and brings JVM's behavior back to only reserving 4MB for initial Metaspace and then growing it based on need.

We can thus measure the *actual* memory needs of a Java application.  Indeed, profiling Java memory usage of `showinf` with `-XX:+UnlockDiagnosticVMOptions -XX:+PrintGCDetails -XX:+PrintGCTimeStamps` shows that we are *far* below the 1.5GB default reservation (about 100MB total)::

    Heap
     def new generation   total 74944K, used 9417K [0x00007f1391000000, 0x00007f1396150000, 0x00007f139baa0000)
      eden space 66624K,  14% used [0x00007f1391000000, 0x00007f1391928990, 0x00007f1395110000)
      from space 8320K,   0% used [0x00007f1395110000, 0x00007f1395119ce0, 0x00007f1395930000)
      to   space 8320K,   0% used [0x00007f1395930000, 0x00007f1395930000, 0x00007f1396150000)
     tenured generation   total 166592K, used 2940K [0x00007f139baa0000, 0x00007f13a5d50000, 0x00007f13b1000000)
       the space 166592K,   1% used [0x00007f139baa0000, 0x00007f139bd7f2c8, 0x00007f139bd7f400, 0x00007f13a5d50000)
     Metaspace       used 15517K, capacity 15572K, committed 15616K, reserved 16384K

Profiling also "native" memory usage with `-XX:+UnlockDiagnosticVMOptions -XX:NativeMemoryTracking=summary -XX:+PrintNMTStatistics` adds another 200MB, bringing the per-process total to around 300MB::

    Native Memory Tracking:

    Total: reserved=2738926KB, committed=288950KB
    -                 Java Heap (reserved=2445312KB, committed=249856KB)
                                (mmap: reserved=2445312KB, committed=249856KB)

    -                     Class (reserved=16618KB, committed=15850KB)
                                (classes #2164)
                                (malloc=234KB #876)
                                (mmap: reserved=16384KB, committed=15616KB)

    -                    Thread (reserved=10324KB, committed=10324KB)
                                (thread #10)
                                (stack: reserved=10280KB, committed=10280KB)
                                (malloc=32KB #52)
                                (arena=12KB #20)

    -                      Code (reserved=250027KB, committed=3419KB)
                                (malloc=427KB #1090)
                                (mmap: reserved=249600KB, committed=2992KB)

    -                        GC (reserved=7975KB, committed=831KB)
                                (malloc=7KB #80)
                                (mmap: reserved=7968KB, committed=824KB)

    -                  Compiler (reserved=134KB, committed=134KB)
                                (malloc=3KB #48)
                                (arena=131KB #3)

    -                  Internal (reserved=1450KB, committed=1450KB)
                                (malloc=1418KB #3055)
                                (mmap: reserved=32KB, committed=32KB)

    -                    Symbol (reserved=3890KB, committed=3890KB)
                                (malloc=3019KB #31242)
                                (arena=871KB #1)

    -    Native Memory Tracking (reserved=575KB, committed=575KB)
                                (malloc=3KB #35)
                                (tracking overhead=572KB)

    -               Arena Chunk (reserved=2622KB, committed=2622KB)
                                (malloc=2622KB)

Just reserving at least 1.5GB of RAM per `java` process would thus be a total waste.

Now, `showinf` is just a shell script which in turns calls `/usr/local/lib/bftools/bf.sh` to do the actual work of running the JVM.  Script `bf.sh` builds the JVM command-line using environment variables; we can thus insert arbitrary JVM options by setting `BF_FLAGS`.  The heap size instead *must* be set using `BF_MAX_MEM`: leaving this unset will direct `bf.sh` to use the built-in default `512m`.

**Note** that the dynamically growing part of the Java memory is now the "Metaspace": heap size is fixed by `-Xmx$BF_MAX_MEM`; therefore, some leeway must be given for it to grow as necessary.  So, contrary to what my first comment in this thread states, `BF_MAX_MEM` should not be set to *amount of total memory for the job - 400 MB* because that would basically cap Metaspace growth to ~300MB. I'm afraid I know no good rule to do the split, but it looks like that, for processing a single image, 512MB (the `BF_MAX_MEM` default) are more than enough so I'll leave it like that and use the rest memory for the Metaspace.

*(As a side note: this shows that the JVM is heavily tuned for long-running server applications which have unrestricted access to system resources.  Running it for short-lived command-line jobs (resource-limited by the cluster scheduler) is just asking for trouble.)*
